services:
  vt_tool_web:
    init: true
    restart: always
    env_file:
      - ../.env
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    ports:
      - "127.0.0.1:${VT_TOOL_WEB_PORT:-8080}:8080"
    networks:
      - vt_tool_network


  misp-core:
    init: true
    restart: always
    ports:
      - "${CORE_HTTP_PORT:-80}:80"
      - "${CORE_HTTPS_PORT:-443}:443"
    env_file:
      - ${MISP_PATH}/.env
    volumes:
      - "${MISP_PATH}/core/configs/:/var/www/MISP/app/Config/:Z"
      - "${MISP_PATH}/core/logs/:/var/www/MISP/app/tmp/logs/:Z"
      - "${MISP_PATH}/core/files/:/var/www/MISP/app/files/:Z"
      - "${MISP_PATH}/core/ssl/:/etc/nginx/certs/:Z"
      - "${MISP_PATH}/core/gnupg/:/var/www/MISP/.gnupg/:Z"
      - "misp_guard_ca:/usr/local/share/ca-certificates/misp_guard:Z"
    # customize by replacing ${CUSTOM_PATH} with a path containing 'files/customize_misp.sh'
    # - "${CUSTOM_PATH}/:/custom/:Z"
    # mount custom ca root certificates
    # - "./rootca.pem:/usr/local/share/ca-certificates/rootca.crt:Z"
    networks:
      - vt_tool_network

  misp-modules:
    init: true
    restart: always
    volumes:
      # custom MISP modules are loaded at startup time
      - "${MISP_PATH}/modules/custom/action_mod/:/custom/action_mod/:Z"
      - "${MISP_PATH}/modules/custom/expansion/:/custom/expansion/:Z"
      - "${MISP_PATH}/modules/custom/export_mod/:/custom/export_mod/:Z"
      - "${MISP_PATH}/modules/custom/import_mod/:/custom/import_mod/:Z"
    networks:
      - vt_tool_network

  misp-guard:
    init: true
    restart: always
    ports:
      - "${GUARD_PORT:-8888}:${GUARD_PORT:-8888}"
    environment:
      - "GUARD_PORT=${GUARD_PORT:-8888}"
      - "GUARD_ARGS=${GUARD_ARGS}"
    volumes:
      - "${MISP_PATH}/guard/config.json:/config.json:ro"
      - misp_guard_ca:/misp_guard_ca
    networks:
      - vt_tool_network

  mail:
    restart: always
    environment:
      # Generic SMTP relay
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"
    networks:
      - vt_tool_network

networks:
  vt_tool_network:
    external: true
    name: ${NETWORK_NAME}

volumes:
  misp_guard_ca: